### ISSUE TITLE
[Bug] Searching bank for bank tag not supported.

### ISSUE THREAD

**Issue by Aggermor** [geheur/bank-multisearch#2]
This plugin is not compatible with [Bank Tag plugin](https://github.com/runelite/runelite/wiki/Bank-Tags).
When searching the bank for a `bank tag` is not shown as expected.
Following screenshots is _expected_ behavior but with this plugin enabled, no items belonging to a `tag` are shown. 

![image](https://github.com/user-attachments/assets/11b16656-1ce5-4c83-a347-82c75c86cc85)
![image](https://github.com/user-attachments/assets/6eefc01a-804f-4535-abaf-cad27d35c630)

**Comment by geheur** [comment]
Will be fixed in 1.0.2 (in that you can search for bank tags like normal. you can't search for bank tags as well as other things).
